[project]
name = "zoedepth"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "matplotlib",
    "opencv-python",
]

[tool.setuptools.packages.find]
include = ["metric_depth/zoedepth*"]